Feature/rev 10787
revosystems/sidecar pull request #39
Opened 2023-04-13 20:22 UTC by PauBenetPrat

https://linear.app/revo/issue/REV-10787/801-corregir-el-formato-de-numeros-puntoscomas-al-exportar-datos-en

2023-04-14 06:23 UTC, adriamt approved these changes

2023-04-14 06:32 UTC, MartiSalaMorral approved these changes

2023-04-14 10:48 UTC, BadChoice requested changes

2023-04-14 10:48 UTC, BadChoice commented on resources/views/widgets/table.blade.php
> -                    {!! $field->toHtml($row) !!}
ui, vols dir que hem de passar el value?

2023-04-14 10:48 UTC, BadChoice commented on src/Enums/ComputedDisplayFormat.php
> +    case CURRENCY;
i si en comptes de fer l'enum, fem un displayFormat(Currency::class) i llavors podrem fer 

function toHtml($row){
  (new $displayFormat)->toHtml($row)

2023-04-14 10:48 UTC, BadChoice commented on src/ExportFields/Computed.php
> +    protected ComputedDisplayFormat $displayFormat;
aixo que sigui la classe, així ens servira per qualsevol field

2023-04-14 10:49 UTC, BadChoice requested changes

2023-04-14 10:49 UTC, BadChoice commented on composer.json
> +        "php": "^8.1",
si ens carreguem l'enum podem deixar 8.0

2023-04-14 14:44 UTC, PauBenetPrat commented
Fet, ja ho podeu acabar  de revisar si voleu ;)

2023-04-17 07:07 UTC, BadChoice approved these changes

2023-04-17 07:07 UTC, merged