GroupBy week and year datetime corrections.
revosystems/sidecar pull request #54
Opened 2024-07-10 09:39 UTC by aleixgil

https://linear.app/revo/issue/REV-16319/8195-error-500-en-filtrar-per-mes-al-llistat-de-canals#comment-68d0911b

2024-07-11 07:39 UTC, MartiSalaMorral commented
Els canvis no estan malament però m'hauràs d'explicar com és que s'han hagut de fer perquè sense context no puc dir-hi res...

2024-07-11 07:39 UTC, MartiSalaMorral approved these changes

2024-07-15 08:45 UTC, MartiSalaMorral approved these changes

2024-07-15 08:52 UTC, JordiFL-Revo approved these changes

2024-07-16 07:13 UTC, BadChoice requested changes

2024-07-16 07:13 UTC, BadChoice commented on src/ExportFields/BusinessDateTime.php
> +                return DB::raw("DATE(SUBTIME(CONVERT_TZ({$field}, 'UTC', '{$timezone}'), '{$openingTime}')) as {$this->dependsOnField}");
ui no, el field pot no ser el bo, el bo ha de ser el dependsonField si de cas afegitm el GS_orders. davant del depends on field (hi ha d'havier alguna funcio que ens ho faci ja (per el field)

2024-07-16 07:13 UTC, BadChoice commented on src/Filters/GroupBy.php
> -            return $query->groupBy(DB::raw('year(' . $this->subTime($key, Date::getUtcOpeningTime()) . ')'))
el SUBTIME peta amb sqllite per aixo esta sobrescrit, si de cas portem lo de xef aqui al paquet perque estigui per a tothom

2024-07-16 07:21 UTC, MartiSalaMorral commented on src/ExportFields/BusinessDateTime.php
> +                return DB::raw("DATE(SUBTIME(CONVERT_TZ({$field}, 'UTC', '{$timezone}'), '{$openingTime}')) as {$this->dependsOnField}");
El nom de la variable no està massa bé. S'inicialitza així:

`$field = (DB::connection()->getTablePrefix() ?? "") . $this->databaseTable().'.'.$this->dependsOnField;`

2024-07-16 07:29 UTC, BadChoice approved these changes

2024-07-16 07:29 UTC, merged

2024-07-16 07:30 UTC, aleixgil commented on src/Filters/GroupBy.php
> -            return $query->groupBy(DB::raw('year(' . $this->subTime($key, Date::getUtcOpeningTime()) . ')'))
Comentat i és ok.

2024-07-16 07:30 UTC, aleixgil commented on src/ExportFields/BusinessDateTime.php
> +                return DB::raw("DATE(SUBTIME(CONVERT_TZ({$field}, 'UTC', '{$timezone}'), '{$openingTime}')) as {$this->dependsOnField}");
Comentat i és ok.